#
#   存放共有配置文件的地方
#

#server
server:
#  端口号
  port: 8888

#spring
spring:
  application:
    name: study-utils

  #  环境配置---  application-prod.xml 启用生产环境的配置
  profiles:
    active: prod

  #数据配置
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat,wall,logging
      # logging 是打印日志的配置名
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/mama-bike?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
      #用户名
      username: root
      #密码
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,log4j
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true


#mybatis配置
mybatis:
  #    xml文件路径
  mapper-locations: classpath:com/studyUtils/studyUtils/**/*Mapper.xml
  #    实体类路径
  type-aliases-package: classpath:com.studyUtils.studyUtils.**.entity